# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.us/us/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'

describe "whois.nic.us", :aggregate_failures do

  subject do
    file = fixture("responses", "whois.nic.us/us/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file), host: "whois.nic.us")
    Whois::Parser.parser_for(part)
  end

  it "matches status_registered.expected" do
    expect(subject.domain).to eq("nasa.us")
    expect(subject.domain_id).to eq("D668515-US")
    expect(subject.status).to eq(["clientDeleteProhibited", "serverTransferProhibited", "inactive"])
    expect(subject.available?).to eq(false)
    expect(subject.registered?).to eq(true)
    expect(subject.created_on).to be_a(Time)
    expect(subject.created_on).to eq(DateTime.parse("2002-04-18T18:53:15Z"))
    expect(subject.updated_on).to be_a(Time)
    expect(subject.updated_on).to eq(DateTime.parse("2008-02-06T18:39:04Z"))
    expect(subject.expires_on).to be_a(Time)
    expect(subject.expires_on).to eq(DateTime.parse("2103-12-15T23:59:59Z"))
    expect(subject.registrar).to be_a(Whois::Parser::Registrar)
    expect(subject.registrar.id).to eq("10010")
    expect(subject.registrar.name).to eq(".us Reserve Account A")
    expect(subject.registrar.url).to eq("https://www.about.us")
    expect(subject.registrant_contacts).to be_a(Array)
    expect(subject.registrant_contacts.size).to eq(1)
    expect(subject.registrant_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.registrant_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_REGISTRANT)
    expect(subject.registrant_contacts[0].id).to eq("C7065049-US")
    expect(subject.registrant_contacts[0].name).to eq("Patricia Dunnington")
    expect(subject.registrant_contacts[0].organization).to eq("NASA")
    expect(subject.registrant_contacts[0].address).to eq("Office of the CIO, 300 E Street SW")
    expect(subject.registrant_contacts[0].city).to eq("Washington")
    expect(subject.registrant_contacts[0].zip).to eq("20546")
    expect(subject.registrant_contacts[0].state).to eq("DC")
    expect(subject.registrant_contacts[0].country_code).to eq("US")
    expect(subject.registrant_contacts[0].phone).to eq("+1.2023581824")
    expect(subject.registrant_contacts[0].fax).to eq("+1.2023583017")
    expect(subject.registrant_contacts[0].email).to eq("pat.dunnington@nasa.gov")
    expect(subject.admin_contacts).to be_a(Array)
    expect(subject.admin_contacts.size).to eq(1)
    expect(subject.admin_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.admin_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_ADMINISTRATIVE)
    expect(subject.admin_contacts[0].id).to eq("C647383-US")
    expect(subject.admin_contacts[0].name).to eq("Registry Services, LLC")
    expect(subject.admin_contacts[0].organization).to eq("")
    expect(subject.admin_contacts[0].address).to eq("100 S. Mill Ave, Suite 1600")
    expect(subject.admin_contacts[0].city).to eq("Tempe")
    expect(subject.admin_contacts[0].zip).to eq("85281")
    expect(subject.admin_contacts[0].state).to eq("AZ")
    expect(subject.admin_contacts[0].country_code).to eq("US")
    expect(subject.admin_contacts[0].phone).to eq("+1.4806519999")
    expect(subject.admin_contacts[0].email).to eq("help@about.us")
    expect(subject.technical_contacts).to be_a(Array)
    expect(subject.technical_contacts.size).to eq(1)
    expect(subject.technical_contacts[0]).to be_a(Whois::Parser::Contact)
    expect(subject.technical_contacts[0].type).to eq(Whois::Parser::Contact::TYPE_TECHNICAL)
    expect(subject.technical_contacts[0].id).to eq("C647383-US")
    expect(subject.technical_contacts[0].name).to eq("Registry Services, LLC")
    expect(subject.technical_contacts[0].organization).to eq("")
    expect(subject.technical_contacts[0].address).to eq("100 S. Mill Ave, Suite 1600")
    expect(subject.technical_contacts[0].city).to eq("Tempe")
    expect(subject.technical_contacts[0].zip).to eq("85281")
    expect(subject.technical_contacts[0].state).to eq("AZ")
    expect(subject.technical_contacts[0].country_code).to eq("US")
    expect(subject.technical_contacts[0].phone).to eq("+1.4806519999")
    expect(subject.technical_contacts[0].email).to eq("help@about.us")
    expect(subject.nameservers).to be_a(Array)
    expect(subject.nameservers.size).to eq(0)
  end
end
